[Settings]
ID = "f245e11c-585e-470f-b14d-e374f2f3a575"
# Settings in the [build] context are global and are applied to all contexts unless otherwise overridden by more specific contexts.  
[build]
  # This is the directory to change to before starting a build.
  base    = "port"
  # NOTE: This is where we will look for package.json/.nvmrc/etc, not root.
  # This is the directory that you are publishing from (relative to root of your repo)
  publish = "port/build/"
  # This will be your default build command
  command = "echo 'default context'"